### ISSUE TITLE
Failed to execute index do to _id fields?

### ISSUE THREAD

**Issue by datermine** [usesold/elmongo#25]
I'm getting this stack trace (where MY_MONGO_DOC = {"_id":"5754bb23b07e2a082cf40155", ... }):

```
[2016-06-05 19:52:06,609][DEBUG][action.index             ] [Glitch] failed to execute [index {[development--threadclips][threadclips][5754bb23b07e2a082cf40155], source[$MY_MONGO_DOC]}] on [[development--threadclips][3]]
MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]
	at org.elasticsearch.index.mapper.DocumentParser.parseObject(DocumentParser.java:204)
	at org.elasticsearch.index.mapper.DocumentParser.parseDocument(DocumentParser.java:122)
	at org.elasticsearch.index.mapper.DocumentMapper.parse(DocumentMapper.java:309)
	at org.elasticsearch.index.shard.IndexShard.prepareIndex(IndexShard.java:580)
	at org.elasticsearch.index.shard.IndexShard.prepareIndexOnPrimary(IndexShard.java:559)
	at org.elasticsearch.action.index.TransportIndexAction.prepareIndexOperationOnPrimary(TransportIndexAction.java:212)
	at org.elasticsearch.action.index.TransportIndexAction.executeIndexRequestOnPrimary(TransportIndexAction.java:224)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:158)
	at org.elasticsearch.action.index.TransportIndexAction.shardOperationOnPrimary(TransportIndexAction.java:66)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryPhase.doRun(TransportReplicationAction.java:639)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:279)
	at org.elasticsearch.action.support.replication.TransportReplicationAction$PrimaryOperationTransportHandler.messageReceived(TransportReplicationAction.java:271)
	at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:75)
	at org.elasticsearch.transport.TransportService$4.doRun(TransportService.java:376)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Has something changed in ElasticSearch and does ElMongo need to remove this mongodb field now?

**Comment by datermine** [comment]
The actual exception is:

`MapperParsingException[Field [_id] is a metadata field and cannot be added inside a document. Use the index API request parameters.]`
